"""add_transaction_model

Revision ID: 0003_add_transaction_model
Revises: 0002_balance_numeric
Create Date: 2026-05-18

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0003_add_transaction_model'
down_revision: Union[str, None] = '0002_balance_numeric'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE IF EXISTS transactions CASCADE")
    op.execute("DROP TYPE IF EXISTS transactiontype CASCADE")
    op.execute("DROP TYPE IF EXISTS transactionstatus CASCADE")
    
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('transaction_type', sa.Enum('CREDIT', 'DEBIT', 'TRANSFER', name='transactiontype'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', 'REVERSED', name='transactionstatus'), nullable=False),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transactions_account', 'transactions', ['account_id'], unique=False)
    op.create_index('ix_transactions_created', 'transactions', ['created_at'], unique=False)
    op.create_index('ix_transactions_type_status', 'transactions', ['transaction_type', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transactions_type_status', table_name='transactions')
    op.drop_index('ix_transactions_created', table_name='transactions')
    op.drop_index('ix_transactions_account', table_name='transactions')
    op.drop_table('transactions')
    # ### end Alembic commands ###
