"""add_modules_v2

Revision ID: 07c1354b04e0
Revises: 0004_add_schedules
Create Date: 2026-05-20 16:58:31.582068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '07c1354b04e0'
down_revision: Union[str, None] = '0004_add_schedules'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('record_type', postgresql.ENUM('PAYABLE', 'RECEIVABLE', name='recordtype', create_type=False), nullable=False),
    sa.Column('contact_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('original_amount', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('remaining_amount', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'PARTIAL', 'SETTLED', 'CANCELLED', name='advancestatus'), nullable=False),
    sa.Column('issue_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_advances_account_status', 'advances', ['account_id', 'status'], unique=False)
    op.create_table('cash_registers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('operator_id', sa.UUID(), nullable=True),
    sa.Column('opening_balance', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('closing_balance', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', name='cashregisterstatus'), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cash_registers_account_status', 'cash_registers', ['account_id', 'status'], unique=False)
    op.create_table('bank_statement_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('import_batch', sa.String(length=64), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('bank_ref', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'MATCHED', 'MANUAL', 'IGNORED', name='bankstatementstatus'), nullable=False),
    sa.Column('matched_tx_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['matched_tx_id'], ['transactions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bank_statement_account_batch', 'bank_statement_entries', ['account_id', 'import_batch'], unique=False)
    op.create_index('ix_bank_statement_status', 'bank_statement_entries', ['status'], unique=False)
    op.create_table('contracts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('contact_name', sa.String(length=255), nullable=False),
    sa.Column('contact_doc', sa.String(length=20), nullable=True),
    sa.Column('record_type', postgresql.ENUM('PAYABLE', 'RECEIVABLE', name='recordtype', create_type=False), nullable=False),
    sa.Column('total_value', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('installments', sa.Integer(), nullable=False),
    sa.Column('frequency', postgresql.ENUM('MONTHLY', 'WEEKLY', 'YEARLY', 'DAILY', name='frequency', create_type=False), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'EXPIRED', 'CANCELLED', name='contractstatus'), nullable=False),
    sa.Column('recurring_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recurring_id'], ['recurring_transactions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_contracts_account_status', 'contracts', ['account_id', 'status'], unique=False)
    op.create_table('pdv_sales',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cash_register_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('payment_method', sa.Enum('CASH', 'PIX', 'DEBIT_CARD', 'CREDIT_CARD', 'CHECK', 'OTHER', name='paymentmethod'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['cash_register_id'], ['cash_registers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pdv_sales_created', 'pdv_sales', ['created_at'], unique=False)
    op.create_index('ix_pdv_sales_register', 'pdv_sales', ['cash_register_id'], unique=False)
    op.create_table('advance_write_offs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('advance_id', sa.UUID(), nullable=False),
    sa.Column('scheduled_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('write_off_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['advance_id'], ['advances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scheduled_id'], ['scheduled_transactions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('budgets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('contact_name', sa.String(length=255), nullable=False),
    sa.Column('contact_doc', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SENT', 'APPROVED', 'REJECTED', 'EXPIRED', name='budgetstatus'), nullable=False),
    sa.Column('contract_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_budgets_account_status', 'budgets', ['account_id', 'status'], unique=False)
    op.create_table('sales_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('customer_doc', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'CONFIRMED', 'INVOICED', 'CANCELLED', name='salesorderstatus'), nullable=False),
    sa.Column('invoice_number', sa.String(length=100), nullable=True),
    sa.Column('nfe_key', sa.String(length=50), nullable=True),
    sa.Column('nfe_status', sa.String(length=50), nullable=True),
    sa.Column('scheduled_id', sa.UUID(), nullable=True),
    sa.Column('issue_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['scheduled_id'], ['scheduled_transactions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sales_orders_account_status', 'sales_orders', ['account_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sales_orders_account_status', table_name='sales_orders')
    op.drop_table('sales_orders')
    op.drop_index('ix_budgets_account_status', table_name='budgets')
    op.drop_table('budgets')
    op.drop_table('advance_write_offs')
    op.drop_index('ix_pdv_sales_register', table_name='pdv_sales')
    op.drop_index('ix_pdv_sales_created', table_name='pdv_sales')
    op.drop_table('pdv_sales')
    op.drop_index('ix_contracts_account_status', table_name='contracts')
    op.drop_table('contracts')
    op.drop_index('ix_bank_statement_status', table_name='bank_statement_entries')
    op.drop_index('ix_bank_statement_account_batch', table_name='bank_statement_entries')
    op.drop_table('bank_statement_entries')
    op.drop_index('ix_cash_registers_account_status', table_name='cash_registers')
    op.drop_table('cash_registers')
    op.drop_index('ix_advances_account_status', table_name='advances')
    op.drop_table('advances')
    # ### end Alembic commands ###
